# Generated by cucumber-sinatra. (2010-12-05 21:38:25 -0200)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app/requests/')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = RubyCasts

class RubyCastsWorld
  include Capybara
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  RubyCastsWorld.new
end
